# Triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Functions
jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NPM Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist/
  # Deploy Job
  deploy_to_ghp:
    name: Deploy Github Page
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist/
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: ./dist/
  # Deploy to remote Job
  deploy_to_website:
    name: Deploy to Website
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: actions/checkout@v3
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist/
      - name: file location 
        run: pwd
        working-directory: ./dist/
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --progress
          path: ./dist/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}